### ISSUE TITLE
Name conflicts when building MOM5 and MOM6 together

### ISSUE THREAD

**Issue by yvikhlya** [GEOS-ESM/GEOSgcm#116]
When I build the coupled model with MOM6 (along with MOM5) and choose to run MOM6 in AGCM.rc, the model runs MOM6_GEOSPlug, but it calls ocean_model_init from MOM5(libmom.a), since top level module name and subroutine names are the same in libmom.a and libmom6.a. Other name conflicts are also possible. When I build the coupled model with MOM5 only, MOM6_GEOSPlug is not present and get replaced with the stub. We need a possibility to stub one of the MOM5 or MOM6 plug when both are present. Any idea how to resolve these conflicts correct way?

**Comment by tclune** [comment]
I think that in theory if we do the CMake dependencies correctly, the two libraries should not "see" each others modules.   It might be useful to try to replicate with gfortran.  Intel is sometimes overzealous in finding .mod files.

**Comment by yvikhlya** [comment]
@tclune Tom, coupled model does not work with gfortran. This is not related to MOM. It crashes on reading sea ice grid, which we were writing wrong way for a long time. We are reading it wrong way too, that is why ifort works, but gfortran does not.

**Comment by sanAkel** [comment]
If the sea ice grid was never read correctly, it should be a new issue. @yvikhlya please document it with a new Issue. Thanks!

**Comment by yvikhlya** [comment]
@sanAkel It was never read correctly, but now it is not straight forward to correct it. If we do it the right way, all v2 and v3 runs will crash.

**Comment by sanAkel** [comment]
So what shall we do with gfortran? 
> 
> @tclune Tom, coupled model does not work with gfortran. This is not related to MOM. It crashes on reading sea ice grid, which we were writing wrong way for a long time. We are reading it wrong way too, that is why ifort works, but gfortran does not.

@yvikhlya the whole point of documenting these in an issue is to fix them, some day!

**Comment by yvikhlya** [comment]
@sanAkel I agree with you.

**Comment by tclune** [comment]
> So what shall we do with gfortran?
> 
> > @tclune Tom, coupled model does not work with gfortran. This is not related to MOM. It crashes on reading sea ice grid, which we were writing wrong way for a long time. We are reading it wrong way too, that is why ifort works, but gfortran does not.
> 
> @yvikhlya the whole point of documenting these in an issue is to fix them, some day!

Yes, but the gfortran aspect in this thread should probably be a separate issue.   It was only suggested as a diagnostic tool in this thread.

**Comment by yvikhlya** [comment]
@tclune Yes, it should be a separate issue. I am doing it.

**Comment by yvikhlya** [comment]
Opened a separate issue https://github.com/GEOS-ESM/GMAO_Shared/issues/85

**Comment by sanAkel** [comment]
@tclune, @mathomp4 is it possible to fix the cmakelists so to avoid these conflicts? I removed MOM5, only keeping MOM6. Also got rid of references to MOM5 in the guest ocean GC.

https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/bugfix/sanAkel/%23115_and_%23116-coupledModel-issues/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp

** as we discussed in the ticket, please let's get the infrastructure working with MOM6 ** then we can explore ways to cohabitate > 1 ocean model thru the guest ocean GC interface, or a modification thereof. 

** I don't know if other issue  https://github.com/GEOS-ESM/GEOSgcm/issues/115 presents issues that need to be disentangled. But laying it *here* so you can see *both*

**Comment by tclune** [comment]
@sanAkel I am unaware of any fundamental reason why we cannot simultaneously build both MOMs  presuming that both can build with the same single version of FMS.     If I understand the issue reported at the top of the thread, it should just be a matter of being a bit more careful telling CMake the correct dependencies.    The reason I wanted to explore with GFortran is that we have seen Intel be very creative at finding things in unintended directories.   Just wanted to eliminate the possibility that it was an Intel "bug" rather than a mistake in our CMake vs something fundamentally not possible.

Could someone give me precise instructions for replicating the issue?   I'd like to poke around at the CMake to understand what is happening.

**Comment by yvikhlya** [comment]
@tclune To replicate the issue, you would need to run a coupled model with MOM6 and MOM5 build together. For this, you need to clone v10.8.0 of GEOSgcm fixture, then use 
```
/home/yvikhlia/aogcm/coupled/Jason/GEOSgcm/MOM6.cfg
```
to checkout externals, this will get you correct versions of GEOSgcm_GridComp and FMS. Then you need to clone my experiment at
```
~yvikhlia/geos5/mom6-test
```
Sorry, but i don't know the easy way to do the clone, @sanAkel was able to do this. Then, when you run MOM6_GEOSPlug, it calls ocean_model_init from MOM5, though it is not supposed to. 
@mathomp4 and @bena-nasa are aware of this problem.

**Comment by sanAkel** [comment]
@tclune, following are @mathomp4 's instructions to build on sles 11 or 12:

"git clone -b feature/mathomp4/mom6-with-mapl2-2020Mar25 git@github.com:GEOS-ESM/GEOSgcm.git
cd GEOSgcm
mepo init
mepo clone

You then build it like a normal model with cmake, etc."

# SLES 12
mkdir build-Debug-SLES12; cd build-Debug-SLES12
cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_INSTALL_PREFIX=../install-Debug-SLES12 -DCMAKE_BUILD_TYPE=Debug
make -j4 install

- You can see the README and checkout "GEOSgcm" at /discover/nobackup/sakella/geosMom6/Mar26_2020/ 
 -- though for this build in this path has MOM5 moved away (/discover/nobackup/sakella/geosMom6/Mar26_2020/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp) 

- if you build with @mathomp4 's above instructions, most probably you will also get the MOM6plug calling MOM5 modules, as @yvikhlya and later myself got it.

- My clone from @yvikhlya is at /discover/nobackup/sakella/t1
 -- it is a 1x1 deg configuration. But with MOM6 one is not so restricted to proc layout (as with MOM5). 

Regardless of the resolution/configuration, there likely seems some issues (cmake/ifort/bugs in our code...?) Please let us know what you unearth! Thanks!

**Comment by tclune** [comment]
@sanAkel Starting in on this issue this morning.    But am immediately confused.   The instructions only provide me with MOM6.    Can someone give me a tag that demonstrates the MOM5 + MOM6 issue?      Some of the lower bullets in your message hint that there is a directory on discover that does this, but ...

**Comment by sanAkel** [comment]
@tclune just to be sure:

Above Instructions (originally from @mathomp4) 
"
git clone -b feature/mathomp4/mom6-with-mapl2-2020Mar25 git@github.com:GEOS-ESM/GEOSgcm.git

cd GEOSgcm
mepo init
mepo clone

"

Should have both MOM5 and MOM6 at:

/GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp


├── CMakeLists.txt
├── GuestOcean_GridComp.F90
├── MOM6_GEOSPlug
│   ├── CMakeLists.txt
│   ├── @mom6
│   └── MOM6_GEOSPlug.F90
└── MOM_GEOS5PlugMod_getRid   <-you should have " MOM_GEOS5PlugMod", I moved it away
    ├── CMakeLists.txt
    ├── @mom
    └── MOM_GEOS5PlugMod.F90

**Comment by sanAkel** [comment]
Perhaps a bit cleaner:

GEOSgcm/src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/

.
├── CMakeLists.txt
├── GuestOcean_GridComp.F90
├── MOM6_GEOSPlug
└── MOM_GEOS5PlugMod_getRid

**Comment by tclune** [comment]
Hmm.   I have MOM6 and not MOM5.    And I do see the MOM5 entry in the mepo yaml file, so am wondering if maybe something went wrong with the mepo clone.   I would have investigate there but simply assumed I did not have the right branch/tag.

Will update you when I know more.

**Comment by tclune** [comment]
Weird.  2nd attempt has those directories.   So unless the build itself somehow deleted them, I have no idea how I ended up with something partial.   Building again now.

**Comment by yvikhlya** [comment]
@tclune The branch  which Rahul left has both, MOM5 and MOM6, and this is what we want, we just can't build them both together into same executable. Ideally, we want to have an option to build one or another.

**Comment by sanAkel** [comment]
With @aerorahul we `built' a single build and run time option to switch. Of course, we never ran it, certainly not myself. So I never knew if that intent was functional. 

For now, I'll gladly take the option to build GEOS with either MOM5 (as default until some TBD date) and then switch default to MOM6.

@tclune if this is an easier thing, let's go ahead with it!

**Comment by aerorahul** [comment]
> @tclune The branch which Rahul left has both, MOM5 and MOM6, and this is what we want, we just can't build them both together into same executable. Ideally, we want to have an option to build one or another.



> @tclune The branch which Rahul left has both, MOM5 and MOM6, and this is what we want, we just can't build them both together into same executable. Ideally, we want to have an option to build one or another.

@yvikhlya That is not true.  I was able to build both together.  I also added code to chose one or the other at runtime.

**Comment by sanAkel** [comment]
yes! all that was done: 
- add MOM6 (GFDL code + plug)
- ability to build with MOM5 and MOM6
- ability to switch between both MOMs at run time.

* But *NONE* of the above were tested. Until RECENTLY!

**Comment by aerorahul** [comment]
> yes! all that was done:
> 
> * add MOM6 (GFDL code + plug)
> * ability to build with MOM5 and MOM6
> * ability to switch between both MOMs at run time.
> 
> * But _NONE_ of the above were tested. Until RECENTLY!

@sanAkel The last statement is only half true.  A run test was performed with existing MOM5_Plug and the changes to the GuestOcean_GridComp (to enable use of  MOM6_Plug at runtime) were found to be bit reproducible.  The test was coordinated with @yvikhlya.  I never tested the MOM6 run compatibility, because the MOM6 was not configured to be run as part of the GEOS environment.

**Comment by sanAkel** [comment]
@aerorahul to repeat in my words, yourself and/or @yvikhlya tested whether following changes leave the MOM5 functionality intact

>add MOM6 (GFDL code + plug)
ability to build with MOM5 and MOM6
ability to switch between both MOMs at run time.
> 

but not the new addition: MOM6. 

And that's where we are now!

**Comment by aerorahul** [comment]
@sanAkel correct.  MOM6_Plug in GEOS was not tested in a run mode.

**Comment by yvikhlya** [comment]
@aerorahul @sanAkel The changes which Rahul made in GuestOcean do not affect the coupled model in the setup which we usually use. We discussed this and both of us doubled checked this. What complicates the debugging process now is that now with recent updates to the model mom5 does not work either. Should we fix MOM5 set up first and then move to MOM6? This would sound reasonable to me.

**Comment by sanAkel** [comment]
@yvikhlya let's check with @bena-nasa on 

> Should we fix MOM5 set up 
> 

In any case, I'm revising the MOM6 plug, because there are things in it that are not correct!

**Comment by yvikhlya** [comment]
> if you could, please do revive MOM5.

I think i start with this. On SLES12.

**Comment by tclune** [comment]
I was wrong about this being an overt problem with dependencies in our CMake scripts;  the problem is inherent due to the use of the same named modules in both versions of MOM.

But ... I demonstrated with a toy example that the use of SHARED for the libraries fixes this problem.   Now, my memory is that we disabled the ecbuild aspect that would otherwise have automatically added the SHARED property to our libraries.    Either way it should be straightforward to manually add that property to one or both MOM libraries.  (Starting with MOM6 because that is the one that is apparently being linked second and then finding the wrong procedure.)

**Comment by tclune** [comment]
Ok - we have a solution of sorts.   On OSX it was sufficient to simply build both mom libraries as shared (requires a few extra lines and an update to @cmake).

However, on Linux that was not sufficient and another step was needed in the run script:
```script
setenv LD_PRELOAD  <install-path>/lib/libmom6.so
```
So robust use will require updates to gcmsetup.j and experiments to see if relative path is sufficient.

**Comment by tclune** [comment]
@sanAkel will be pushing a fix elsewhere.
