### ISSUE TITLE
mpi_finalize failed on sles12

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GEOSgcm#132]
The error message
PMPI_Finalize(367)...............: MPI_Finalize failed
PMPI_Finalize(278)...............: 
MPID_Finalize(1069)..............: 
MPIDI_OFI_mpi_finalize_hook(1626): OFI domain close failed (ofi_init.c:1626:MPIDI_OFI_mpi_finalize_hook:Device or resource busy)

**Comment by mathomp4** [comment]
@weiyuan-jiang Is this solved by GEOS-ESM/MAPL#267?

**Comment by mathomp4** [comment]
Pinging @tclune

**Comment by weiyuan-jiang** [comment]
@mathomp4 No. This is a different issue.

**Comment by mathomp4** [comment]
@weiyuan-jiang Okay. It was a hope

**Comment by weiyuan-jiang** [comment]
Actually this is the issue #258 at MAPL you raised . This may be a problem from compiler or impi. Should I remove this issue? @mathomp4

**Comment by mathomp4** [comment]
@weiyuan-jiang It might be good to have it here as well. Then if GEOS-ESM/MAPL#258 is ever resolved (or vice versa) we'll know about it.

**Comment by mathomp4** [comment]
I believe this is now fixed by MAPL v2.0.6+ and v2.1.1. Closing
