### ISSUE TITLE
module load GEOSenv (SLES11) fails on discover

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/GEOSgcm#156]
Starting very recently I get this error when loading GEOSenv:

```
Lmod has detected the following error:  The following module(s) are unknown:
"other/cmake/3.15.5" "other/git"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "other/cmake/3.15.5" "other/git"

Also make sure that all modulefiles written in TCL start with the string #%Module

Executing this command requires loading "other/git" which failed while processing the
following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    GEOSenv          /discover/swdev/gmao_SIteam/modulefiles-SLES11/GEOSenvExecuting this command requires loading "other/cmake/3.15.5" which failed while
processing the following module(s):

    Module fullname  Module Filename
    ---------------  ---------------
    GEOSenv          /discover/swdev/gmao_SIteam/modulefiles-SLES11/GEOSenv
```

I checked the README for GEOSgcm but the instructions have not changed. Is there a new environment file required for use with GEOSgcm master?

**Comment by lizziel** [comment]
Jonathan, until we get a response from @mathomp4 , go ahead and use my modified GEOSenv file located here:
`~ewlundgr/modulefiles/GEOSenv.ewl`

You also need to add this to your .bashrc and source it before doing module load:
`module use -a ~ewlundgr/modulefiles`

The new file has modified modules for git and cmake. I used module spider to find ones that actually work since the ones included in GEOSenv are no longer available.

**Comment by mathomp4** [comment]
@lizziel My first guess (as I can't see much in your home directory) is that somewhere in a `.tcshrc` or `.bashrc` you have:
```
module use -a /discover/swdev/gmao_SIteam/modulefiles-SLES11
```
That works fine if you are on a SLES 11 node, but the default head node you get on discover now is SLES 12. You need to protect that a la:
```
if [[ -e /etc/os-release ]]
then
   module use -a /discover/swdev/gmao_SIteam/modulefiles-SLES12
else
   module use -a /discover/swdev/gmao_SIteam/modulefiles-SLES11
fi
```
You can't source the SLES 11 GEOSenv on SLES12

**Comment by lizziel** [comment]
Thanks @mathomp4.
