### ISSUE TITLE
Remove GSW as external repository controlled by mepo/externals

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#158]
Per @sanAkel, the MOM6 testing will move to use the GSW contained as a git submodule rather than using a separate fork/repo.

Should be simple to remove.

**Comment by sanAkel** [comment]
Thanks! @mathomp4 

That's right! Plan is to do the **same** for all MOM6 packages, 
https://github.com/NOAA-GFDL/MOM6/tree/dev/gfdl/pkg

**Comment by mathomp4** [comment]
@sanAkel I think GSW was the only one we split out, though. The others I've never seen 😄
