### ISSUE TITLE
Running L132 with Replay Crashes GEOSgcm v10.13.0

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#166]
All,

In looking at #164, @atrayano asked in Teams if I was running Replay. I wasn't, but then I thought I should just in case that also triggers a different error with ESMF Logging. 

Well, the short answer is: I don't know because it crashes. To wit, you get a:
```
Floating point exception: floating-point invalid operation
```
and it traces back to `nh_core.F90`. I can't figure out how to copy-and-paste the traceback in DDT so:
<img width="1708" alt="Screen Shot 2020-06-30 at 11 17 56 AM" src="https://user-images.githubusercontent.com/2982494/86144205-5c691100-bac3-11ea-82a4-c0765e6e17af.png">

I'm not running non-hydrostatic though. Should I even be in nh_core?  I think this is already beyond me so I'll assign people who know more about FV3 and replay than I do.

**Comment by sdrabenh** [comment]
@mathomp4, @wmputman mentioned yesterday that anything other than 72-levels will default to NonHydrostatic. The solution is to run hydrostatic by setting the following in fvcore_layout.rc:
 
&fv_core_nml
 Make_NH = .F.
 k_split = 2
 hydrostatic = .T.
 do_sat_adj = .F.
 z_tracer = .T.
 fv_debug = .F.
 hord_mt = 5
 remap_option = 0
/

**Comment by mathomp4** [comment]
> @mathomp4, @wmputman mentioned yesterday that anything other than 72-levels will default to NonHydrostatic. The solution is to run hydrostatic by setting the following in fvcore_layout.rc:
> 
> &fv_core_nml
> Make_NH = .F.
> k_split = 2
> hydrostatic = .T.
> do_sat_adj = .F.
> z_tracer = .T.
> fv_debug = .F.
> hord_mt = 5
> remap_option = 0
> /

Ah. I'll give it a try. If this is correct, then I might propose an update to `gcm_setup` to change this.

**Comment by mathomp4** [comment]
@sdrabenh @wmputman Okay. That's definitely happier.

SRight now, hydrostatic=true/false is controlled by the horizontal resolution (I think C768 and higher is NH by default).

Some testing shows that by default C12, C24, and C48 all will crash with L132 Replay. C48 is still a useful resolution and as such, I'd like to make `gcm_setup` make usable experiments. I can propose a change to `gcm_setup` if you like, but I'm wondering what should it be.  

Should it be that any resolution `gcm_setup` thinks should be hydrostatic (regardless of number of levels), should be run hydrostatic? This would be C720 and lower.

Or perhaps should it there be a sliding scale? C360 L132 should be non-hydrostatic but C360 L72 should be hydrostatic? If something like that, it would probably be better to have another question to the setup--hydrostatic or non-hydrostatic--where the default changes at whichever resolution(s) @wmputman prefers.

**Comment by sdrabenh** [comment]
> @sdrabenh @wmputman Okay. That's definitely happier.
> 
> Right now, hydrostatic=true/false is controlled by the horizontal resolution (I think C768 and higher is NH by default).
> 
> Some testing shows that by default C12, C24, and C48 all will crash with L132 Replay. C48 is still a useful resolution and as such, I'd like to make `gcm_setup` make usable experiments. I can propose a change to `gcm_setup` if you like, but I'm wondering what should it be.
> 
> Should it be that any resolution `gcm_setup` thinks should be hydrostatic (regardless of number of levels), should be run hydrostatic? This would be C720 and lower.
> 
> Or perhaps should it there be a sliding scale? C360 L132 should be non-hydrostatic but C360 L72 should be hydrostatic? If something like that, it would probably be better to have another question to the setup--hydrostatic or non-hydrostatic--where the default changes at whichever resolution(s) @wmputman prefers.

I think @wmputman will have the best advice. However, my thought would be to make this a question part of gcm_setup whereby the default value for <C360 is hydrostatic and >C720 is non-hydrostatic.

**Comment by wmputman** [comment]
I'd like to have the option made in the setup, for now I tried to default all 72L cases to hydrostatic, and all others to non-hydrostatic.  There some additional choices we need to make depending on the microphysics too for NH. Plus, NH benefits from a rebuild with additional options, but works just fine with the hydrostatic build for reasonable resolutions.  I'm kind of rambling on, in the end whether it's gcm_setup or something else we need to manage the NH options better as more people begin using them.

**Comment by wmputman** [comment]
Here are the key settings:

Hydrostatic:

&fv_core_nml
Make_NH = .F.
k_split = 2
hydrostatic = .T.
do_sat_adj = .F.
z_tracer = .T.
hord_mt = 5
/

NH for 1MOM and MG1:

&fv_core_nml
Make_NH = .T.
k_split = 2
hydrostatic = .F.
do_sat_adj = .F.
nwat = 3
z_tracer = .T.
/

NH for GFDL MP:

&fv_core_nml
Make_NH = .T.
k_split = 2
hydrostatic = .F.
do_sat_adj = .T.
nwat = 6
z_tracer = .T.
/

I also hate having k_split in here but that's another story...

**Comment by sdrabenh** [comment]
@wmputman it sounds like we should add 2 additional questions to gcm_setp: one for MP choice and another for hydrostatic/nonhydrostatic?

**Comment by wmputman** [comment]
Yes, I think that is important

**Comment by sdrabenh** [comment]
@wmputman if we add a MP choice, what are the basic options need to set in AGCM.rc ?

**Comment by sdrabenh** [comment]
...for running MG1 or GFDL ?

**Comment by wmputman** [comment]
It's as simple as setting:

CLDMICRO: GFDL
or
CLDMICRO: 2MOMENT

**Comment by sdrabenh** [comment]
@wmputman that's it?! Okay, great. I'll rework gcm_setup.

**Comment by mathomp4** [comment]
Fixed in v10.14.0. Closing.
