### ISSUE TITLE
GEOSgcm GCC Build is broken

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#177]
For some reason, the latest updates to the GCM broke the CI:
```
Scanning dependencies of target GuestOcean_GridComp
[ 69%] Building Fortran object src/Components/@GEOSgcm_GridComp/GEOSogcm_GridComp/GEOSocean_GridComp/GuestOcean_GridComp/CMakeFiles/GuestOcean_GridComp.dir/GuestOcean_GridComp.F90.o
f951: Fatal Error: Reading module ‘mom6_geosplugmod’ at line 103032 column 47: Expected right parenthesis
compilation terminated.
```
Note if I build on discover with GCC 9.3.0 and Open MPI, it builds just fine.

I did try upticking to GCC 10.1.0 on CircleCI to see if that helped, but no go.

So, I'm a bit lost.

First, @tclune have you ever seen this error? I'm wondering if perhaps it is due to the fact that the `medium` resource class on CircleCI has only 4 GB of memory. Perhaps we just finally tipped over that? 

I'll try doing some more things to see what I can do. Maybe update/change the OS used for the CI Docker images?

**Comment by mathomp4** [comment]
Note: `MOM6_GeosPlugMod` does not have 100000 lines of code 😄

**Comment by mathomp4** [comment]
Update: I think I had a bad test of GCC on Friday. I can confirm it is the GCC build in whole that is broken in v10.14.0

**Comment by atrayano** [comment]
@mathomp4 
The error message rings a bell - but the only thing that comes to mind is that we need to open the "file" with all_pes=.true.. I believe we have fixed these several times
