### ISSUE TITLE
Testing of proto v10.14.0 Release

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#178]
As a *lot* of changes have occurred here, let's make a tracking issue for tests of the proto-v10.14.0 release:

- [x] AMIP
- [x] AMIP regress
- [x] AMIP replay
- [x] AMIP replay regress
- [x] AMIP replay-no-increment
- [ ] AMIP replay-no-increment regress
- [x] MOM5 
- [x] MOM6

**Comment by yvikhlya** [comment]
@mathomp4 @sdrabenh There is inaccuracy in release description:

4. Updated MOM5.

Actually, MOM6 was updated.

**Comment by mathomp4** [comment]
> @mathomp4 @sdrabenh There is inaccuracy in release description:
> 
> 1. Updated MOM5.
> 
> Actually, MOM6 was updated.

Well, technically the *CMake* for MOM5 was updated, but, yes, the code inside was not. I'll make a change to the wording.

**Comment by sdrabenh** [comment]
@yvikhlya would you like mom5 updates removed or is @mathomp4 wording ok?

**Comment by yvikhlya** [comment]
> @yvikhlya would you like mom5 updates removed or is @mathomp4 wording ok?

MOM5 itself was not changed from v10.13.0 to v10.14.0, only CMakeLists. MOM6 plug and @mom6 were added to main (before, they lived on separate branch). Anyway, this is just wording.

**Comment by sanAkel** [comment]
@mathomp4 
I assume that yourself and/or @sdrabenh have already tested v10.14.0 for:
- AMIP
- AMIP regress
- AMIP replay
- AMIP replay-no-increment
- AMIP replay-no-increment regress

**Note:** I would need some help to do such test(s)!

As for:
- MOM5 
- MOM6
myself and @yvikhlya have already tested what was in PR. 


So, really, I'm not sure what this issue is about!
Do you suggest a `fresh` clone of v10.14.0 and repeat **ALL** the above?

**Comment by yvikhlya** [comment]
> @mathomp4
> I assume that yourself and/or @sdrabenh have already tested v10.14.0 for:
> 
>     * AMIP
> 
>     * AMIP regress
> 
>     * AMIP replay
> 
>     * AMIP replay-no-increment
> 
>     * AMIP replay-no-increment regress
> 
> 
> **Note:** I would need some help to do such test(s)!
> 
> As for:
> 
>     * MOM5
> 
>     * MOM6
>       myself and @yvikhlya have already tested what was in PR.
> 
> 
> So, really, I'm not sure what this issue is about!
> Do you suggest a `fresh` clone of v10.14.0 and repeat **ALL** the above?

A bunch of things went into this release besides MOM6, some of them after we merge develop onto MOM6 branch, so it is not bad idea to test everything again. This will not take long.

**Comment by sanAkel** [comment]
Just saw your messages on teams chat. 

I can do the MOM6 testing and perhaps MOM5 as well. First I'll do MOM6.

**Comment by mathomp4** [comment]
@sanAkel Scott will be doing the AMIP tests. I just added you guys to let you know and as the mom masters. 😄

**Comment by sanAkel** [comment]
@mathomp4 both MOM5 and MOM6 ran okay. I hope AMIP tests for @sdrabenh also go well.
