### ISSUE TITLE
Update GEOSgcm to Intel 19.1?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#183]
This is a generic issue asking for opinions (mainly from @wmputman) about moving to Intel 19.1 with GEOSgcm. I'd most likely recommend Intel 19.1.2 (the latest version).

The reasons are many but amongst them are that:

1. GEOSldas requires Intel 19+ on SLES 12 (paging @weiyuan-jiang, @gmao-rreichle)
2. The JEDI folks are also in Intel 19+ land (paging @danholdaway)
3. Perhaps even the Harvard Folks are using it? (paging @lizziel)

Now, one reason we haven't moved is that Intel 18 -> Intel 19 is a non-zero-diff change, but it's probably good to move soon if only to bring ourselves inline with GEOSldas and JEDI. And with non-zero-diff PRs possible soon:

- https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/289
- https://github.com/GEOS-ESM/GEOSgcm_App/pull/154

as well as the move to [GEOSchem_GridComp v.1.4](https://github.com/GEOS-ESM/GEOSchem_GridComp/releases/tag/v1.4.0) which is also possibly non-zero-diff, it might be good to combine these into as ~many~ few EMIPs as possible (paging @sdrabenh)

I'll also ping @tclune in case there are any other Intel 18/19 issues I'm unaware of.

**Comment by mathomp4** [comment]
More reason to advance Intel from @bena-nasa:

> ok so, the final score, mapl_2.1.6 vs mapl develop when running 2 moment physics:
> intel 18.05, non-zero diff
> intel 19.1.0.166, zero-diff
> the intel 21 beta 7 version matt build, zero-diff
> between the fact that change the compiler version, causes and non-zero diff to go away, and the fact that when I was testing this before the intel 18.05 debugged build was zero really points to the 18.05 as the culprit. This seems like a perfect reason to move to 19.1.0166 in addition to the reason Matt lays out in the PR#288

I might let him expand more about his testing, etc here.

**Comment by danholdaway** [comment]
For what it's worth we generally skipped Intel 18 for JEDI due to the number of bugs we were finding that went away with Intel 19 and 20. As such we can only build GEOS with Intel 19 for the work we are doing where GEOS and JEDI are built in the same executables.

**Comment by mathomp4** [comment]
@danholdaway Thanks. I'm hoping to target Intel 19.1.2 (aka 2020 Update 2). Do the JEDI folks have any experience with that version? Hopefully it works?

**Comment by danholdaway** [comment]
@mathomp4 I haven't tried to build the jedi-geos interface with that version but it's the default version of the modules when not linking to GEOS and is works well.

**Comment by mathomp4** [comment]
@danholdaway May I present:
```
/discover/swdev/mathomp4/Models/GEOSgcm-MAPLdevel-Intel1912/GEOSgcm/install-Release
```
I built it with:
```
comp/gcc/8.3.0
comp/intel/19.1.2.254
mpi/impi/19.1.2.254
```
Could you give it a spin?
