### ISSUE TITLE
Enable variant mepo styles

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GEOSgcm#332]
Some tweaks are needed in cmake in a few places to allow variant placement of the "@" character used for mounting subrepositories.

**Comment by mathomp4** [comment]
Per #334, the repos are:

- [x] ESMA_cmake → v3.5.6
- [ ] GEOSgcm
- [ ] GEOSgcm_GridComp
- [ ] FVdycoreCubed_GridComp
- [ ] GEOSchem_GridComp

I'm going to do a test to see if these are safe to dribble in one-by-one into `develop` branches (assuming v3.5.6 is the ESMA_cmake). I think they should be fine to do so.

**Comment by tclune** [comment]
Impacted repos:

- GMAO_Shared
- FVdycoreCubed_GridComp
- GEOSchem_GridComp
