### ISSUE TITLE
GEOSgcm `main` no longer works at NAS

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#376]
As expected, with the adoption of GOCART2G into GEOSgcm, the `main` branch no longer works at NAS. 

As reported by @bena-nasa and myself earlier, this is due to the use of hard-coded discover paths in the boundary condition area. So NAS is trying to find:
```
/discover/nobackup/projects/gmao/share/dao_ops/fvInput/ExtData/chemistry
```

**Comment by tclune** [comment]
They won't change the file system for us?

:-)

**Comment by mathomp4** [comment]
Well, Ben and I could tell rsync to follow symlinks which would just move the data over, but it could cascade into storing a *lot* of duplicate files. Or we could tell it to exclude those symlinks and make our own relative to the data on NAS already, but that was counter to what Arlindo wanted. He wanted the actual files to be in ExtData/chemistry.

I guess for now I'll only do model builds at NAS? It's sort of a waste of SBUs in a way, but I suppose it does at least let us know things build at NAS even if they don't run.
