### ISSUE TITLE
Standalone FV3

### ISSUE THREAD

**Issue by wmputman** [GEOS-ESM/GEOSgcm#38]
for resolutions of c180 and c360 the standalone FV3 core runs just fine.  At c720 and larger grids there is a unusual FMS error that is preventing things from running with the following error traceback that is basically failing on a check to see if this grid file exists 'INPUT/grid_spec.nc',  (which it does):

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
StandAlone_FV3_Dy  000000000279CC1D  Unknown               Unknown  Unknown
libc-2.22.so       00007FFFF57CCFE0  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  0000000002811217  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  000000000279FB51  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  0000000001EA45FF  fms_io_mod_mp_get        7781  fms_io.F90
StandAlone_FV3_Dy  0000000001EB40ED  fms_io_mod_mp_fil        8043  fms_io.F90
StandAlone_FV3_Dy  00000000006A69C9  fv_grid_tools_mod         208  fv_grid_tools.F90
StandAlone_FV3_Dy  00000000006BB14C  fv_grid_tools_mod         675  fv_grid_tools.F90
StandAlone_FV3_Dy  0000000000846325  fv_control_mod_mp         459  fv_control.F90
StandAlone_FV3_Dy  0000000000436252  fv_statemod_mp_fv         574  FV_StateMod.F90
StandAlone_FV3_Dy  00000000004ACFC4  fvdycorecubed_gri        2307  DynCore_GridCompMod.F90
StandAlone_FV3_Dy  000000000109E13B  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  00000000010A1E63  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  00000000013A3375  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  000000000109FADD  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  000000000109F68E  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  000000000109F3C5  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  0000000001112FF4  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  0000000000CACECB  mapl_genericmod_m        4038  MAPL_Generic.F90
StandAlone_FV3_Dy  0000000000CFD4B6  mapl_capgridcompm         477  MAPL_CapGridComp.F90

The tricky part is that even if I try to create the grid during the run, it still will not run, failing to create the grid:

forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
StandAlone_FV3_Dy  000000000279CC1D  Unknown               Unknown  Unknown
libc-2.22.so       00007FFFF57CCFE0  Unknown               Unknown  Unknown
StandAlone_FV3_Dy  000000000066BD87  fv_grid_utils_mod        1342  fv_grid_utils.F90
StandAlone_FV3_Dy  000000000066BB0B  fv_grid_utils_mod        1274  fv_grid_utils.F90
StandAlone_FV3_Dy  00000000006B64F0  fv_grid_tools_mod         678  fv_grid_tools.F90
StandAlone_FV3_Dy  0000000000846325  fv_control_mod_mp         459  fv_control.F90
StandAlone_FV3_Dy  0000000000436252  fv_statemod_mp_fv         574  FV_StateMod.F90
StandAlone_FV3_Dy  00000000004ACFC4  fvdycorecubed_gri        2307  DynCore_GridCompMod.F90

**Comment by bena-nasa** [comment]
Can you provide details, number of cores you are running. Does this only affect the standalone? Have you seen this with the full GEOSagcm? Is the consistently reproducible?

**Comment by bena-nasa** [comment]
Also, where is your standalone fv3 script. I might be useful if this were captured and maintained in the repository so that anyone of us can just run the standalone easily.

**Comment by wmputman** [comment]
The run.j script is here

/discover/nobackup/projects/gmao/osse2/FV3_BW

At c720 this consistently happens at any core count. I have no issues with the full model.

-Bill

________________________________
On: 20 August 2019 16:12, "Ben Auer" <notifications@github.com<mailto:notifications@github.com>> wrote:

Also, where is your standalone fv3 script. I might be useful if this were captured and maintained in the repository so that anyone of us can just run the standalone easily.

**Comment by bena-nasa** [comment]
What is the tag you are noticing this with? Is this the CVS/GNU build or the git/cmake build? Is this on scu11 or scu12. I built Jason-UNSTABLE on SLES12 as it looked like your run script was using Jason-UNSTABLE built on SLES12. I ran c720 at 8x48 on SLES12 without issue.

**Comment by wmputman** [comment]
From the CVS/GNU build, Jason-UNSTABLE.  Where is your executable?

-- Bill Putman

William M Putman
Global Modeling and Assimilation Office
NASA Goddard Space Flight Center
Cell: 240-778-5697
Desk: 301-286-2599

**Comment by bena-nasa** [comment]
/gpfsm/dswdev/bmauer/models/Jason-UNSTABLE/GEOSagcm/Linux/bin, build for SLES12

**Comment by wmputman** [comment]
I get the same error with your build:

/discover/nobackup/projects/gmao/osse2/FV3_BW/scratch_c720_L26_T1_8x48_40ppn_Jason-UNSTABLE-R4_NH.log

-- Bill Putman

William M Putman
Global Modeling and Assimilation Office
NASA Goddard Space Flight Center
Cell: 240-778-5697
Desk: 301-286-2599

**Comment by mathomp4** [comment]
@wmputman Was this resolved?
