### ISSUE TITLE
MOM5 coupled model crashes for C180 (atm) x 1/4 (ocn) resolution

### ISSUE THREAD

**Issue by sanAkel** [GEOS-ESM/GEOSgcm#430]
@yvikhlya has a branch that is a merge of _develop_ and [aogmc_branch](https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/feature/aogcm). He can share his `components.yaml` on what he merged.

He set up a coupled model experiment with ⬆️ at `C180 (atm) x 1/4 (ocn)` resolution to be a perpetual year 2000 free running coupled model experiment: `~yvikhlia/aogcm/s2sv4_00/` and I copied over and _tried_ to run it: `/discover/nobackup/sakella/s2sv4_00`.

I am not sure what exactly is causing the problem, but `MOM` will not initialize! Please see log file at:
`/discover/nobackup/sakella/s2sv4_00/slurm-61465429.out`

>MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
MOMInitialize                                  877
pe=00496 FAIL at line=01799    MAPL_Generic.F90                         <status=1>
MOMInitialize                                  877
pe=00504 FAIL at line=01799    MAPL_Generic.F90                         <status=1>
MOMInitialize                                  877

I am _away_ until 07/15, @yvikhlya plans on trouble shooting it. Submitting _this_ issue, just in case some change from `MAPL` is tripping it: @atrayano, @bena-nasa, @mathomp4 please help @yvikhlya if needed. Thanks!

If this problem is unwieldy at _this_ resolution, I would suggest:
1. Build with current `develop`.
2. Setting up an experiment at `1-deg` resolution (with _old_ land).
3. Of course change layout and try.

Thanks!

**Comment by yvikhlya** [comment]
I remember the issue, but I forgot what caused it. BTW ocean_model_init, which is supposed to run before this crash and print a bunch of printouts from MOM did not even run.

**Comment by sanAkel** [comment]
@mathomp4 your memory is awesome! 😄 Really 🆒 

I reopened that [issue](https://github.com/GEOS-ESM/GEOSgcm/issues/352) 😞

**Comment by sanAkel** [comment]
I can confirm [that](https://github.com/GEOS-ESM/GEOSgcm_App/pull/341) works for both:
- MOM5
- MOM6
