### ISSUE TITLE
scm_setup documentation and enhancement

### ISSUE THREAD

**Issue by narnold1** [GEOS-ESM/GEOSgcm#44]
The SCM setup procedure has changed with the git transition, so at the least the documentation needs to be updated.  Ultimately it would be nice if scm_setup worked like gcm_setup, allowing user to run in install/bin/ and specify experiment directory and SCM case.

**Comment by mathomp4** [comment]
I believe `scm_setup` now does this. Maybe not perfectly, but better than before. Closing.
