### ISSUE TITLE
Simplify manage-externals config files

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GEOSgcm#47]
While ME is a bit strict about the contents of config files, there are a few things that can be done to simplify our existing scripts.      Basically, we can have a DEFAULT section ala

```script
[DEFAULT]
protocol = git
required = True
```

And then delete those 2 lines in each of the sections.

I'm opening the ticket here, but this applies to about a dozen repos that have config files.

**Comment by mathomp4** [comment]
I am closing this as wontfix as we are moving to mepo
