### ISSUE TITLE
GEOSgcm master broken!

### ISSUE THREAD

**Issue by aerorahul** [GEOS-ESM/GEOSgcm#49]
Moving FMS outside of GMAO_Shared and bumping the tag from 1.0.3 to 1.0.9, broke the master on this GEOSgcm fixture.

I don't think the movement of FMS is the issue.
Probably needs a new BASELIBS.  In which case g5_modules in @ env needs to be updated on Discover.  BASELIBS is at 5.1.7

**Comment by mathomp4** [comment]
No. I know the problem. A fix is incoming soon. It was a subtle CMake thing.

**Comment by mathomp4** [comment]
I'm doing a build-and-run test now to make sure.
