### ISSUE TITLE
C12 MOM6 Nightly Runs Failing

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#499]
Last night (and maybe in previous nights, but I've been debugging issues on new discover-cron that have prevented nightly tests from running), all the MOM6 runs failed due to missing files. The files in question are:

```
/discover/nobackup/projects/gmao/ssd/aogcm/ocean_bcs/MOM6/72x36/cice/kmt_cice.bin
/discover/nobackup/projects/gmao/ssd/aogcm/ocean_bcs/MOM6/72x36/cice/grid_cice.bin
```

My guess is that these BCs are being regenerated as I see a `72x36.bad` directory there:

```
$ fd 'kmt_cice|grid_cice'
1440x1080/cice/grid_cice.bin
1440x1080/cice/kmt_cice.bin
1440x1080_V3/cice/grid_cice.bin
1440x1080_V3/cice/kmt_cice.bin
1440x1080_V3/cice/vgrid_cice.bin
1440x1080_newtopo/cice/grid_cice.bin
1440x1080_newtopo/cice/kmt_cice.bin
360x210/cice/grid_cice.bin
360x210/cice/kmt_cice.bin
72x36.bad/cice/grid_cice.bin
72x36.bad/cice/kmt_cice.bin
```

I'm making this issue just so I remember this failure will happen until these files are generated.

And then I imagine the runs might go non-zero-diff. 

And I'll need to update my TinyBCs...

**Comment by yvikhlya** [comment]
@mathomp4 Sorry, Matt, that was my mistake. I was trying to update c12 set up yesterday and moved it in wrong location, in aogcm instead of central location. I moved it back now, so next cron job should not crash.

**Comment by sanAkel** [comment]
@mathomp4 would you please confirm that all is okay now. Thank you @yvikhlya

**Comment by mathomp4** [comment]
@yvikhlya @sanAkel Working! Thanks!
