### ISSUE TITLE
Possible change in low-res saltwater BCs?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#501]
A query for @sanAkel and @yvikhlya when they are back. All my nightly tests for MOM6 failed last night with:
```
Saltwater internal state is already split, good to go!
Error! Found 4864 tiles in openwater. Expect to find 4828 tiles.
Your restarts are probably for a different ocean.
```

Does this perhaps have to do with the work you all (and @atrayano?) have been doing with the low-res ocean? Did the number of tiles change?

If so, I suppose I'll have to re-remap my low res ocean restarts? Right?

**Comment by sanAkel** [comment]
Yes @mathomp4 please use the remapper.

I took whatever we have (from tinyBCs) and remapped. That should work for you too.

(I am always reachable via GitHub!)

**Comment by mathomp4** [comment]
> Yes @mathomp4 please use the remapper.
> 
> I took whatever we have (from tinyBCs) and remapped. That should work for you too.
> 
> (I am always reachable via GitHub!)

Hmm. Okay that got me *part* of the way there. It looks like I have a good ocean. But when I tried remapping I didn't notice that the land all fell apart:

```
/usr/local/intel/oneapi/2021/mpi/2021.6.0/bin/mpirun  -np 56 /gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Release/bin/mk_catchANDcnRestarts.x -model catch -time 2021041600 -in_tilefile /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/Icarus-NLv3/MOM6//CF0012x6C_TM0072xTM0036/CF0012x6C_TM0072xTM0036-Pfafstetter.til -out_bcs /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/Icarus-NLv3/MOM6//CF0012x6C_TM0072xTM0036/ -out_tilefile /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/Icarus-NLv3/MOM6//CF0012x6C_TM0072xTM0036/CF0012x6C_TM0072xTM0036-Pfafstetter.til -out_dir /gpfsm/dnb44/mathomp4/Regrid/MOM6-Remap-2022Dec16-Try2/ -surflay 50.0 -in_wemin 13 -out_wemin 13 -in_rst /gpfsm/dnb44/mathomp4/Regrid/MOM6-Remap-2022Dec16-Try2//InData//catch_internal_rst -out_rst catch_internal_rst.20210416_00z.nc4
 ntiles in target BCs      :       307449
 ntiles in restarts        :       313204
pe=00000 FAIL at line=00815    CatchmentRst.F90                         <In tile number should match>
pe=00000 FAIL at line=00033    mk_catchANDcnRestarts.F90                <status=1>
Abort(0) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0
```
I've tried various ways of getting this to work, but I'm stumped. It's like it can't find the BCs for the land I want come from?

**Comment by sanAkel** [comment]
@mathomp4 1 pm at teams?

**Comment by mathomp4** [comment]
> @mathomp4 1 pm at teams?

Okay

**Comment by yvikhlya** [comment]
@mathomp4 I accidentally deleted a working set of BS's from
```
/discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/Icarus-NLv3/MOM6/CF0012x6C_TM0072xTM0036
```
and can't restore them. A set of BC's which I generated using `make_bcs` do not work and have different number of tiles from a set generated by @sanAkel. I tried this twice. I am investigating a problem.

**Comment by yvikhlya** [comment]
@sanAkel Could you include me in 1pm meeting?

**Comment by mathomp4** [comment]
@yvikhlya Well, in the end, I just need some restarts. If @sanAkel can point me to a set he has that works, good enough for me! It's not like I ever did any science with these. 

Heck, I'm pretty sure the ones I have now are ones he pointed me to! 😄

**Comment by sanAkel** [comment]
Just in case:

My "old" bcs: `/discover/nobackup/sakella/restarts/test_23Nov2022/input/`



and my "new" set: `/discover/nobackup/sakella/restarts/test_23Nov2022/output/`



Remap sandbox: `/discover/nobackup/sakella/restarts/test_23Nov2022`

**Comment by sanAkel** [comment]
> Okay that got me _part_ of the way there. It looks like I have a good ocean. But when I tried remapping I didn't notice that the land all fell apart:

@mathomp4 Talking to @yvikhlya ⬆️ crash with land can be explained!

- @yvikhlya 's BCs are from [v.17.1](https://github.com/GEOS-ESM/GEOSgcm_GridComp/releases/tag/v1.17.1) which **does not** have Atanas's fixes merged. They are part of develop, merged into it around [2 weeks ago](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/663)
- My restarts that you just tried have Atanas's code (when I was testing his PR). As @atrayano nicely 😄 explained he was very careful and only touched the ocean raster and left the land raster untouched- so ocean okay, but land: crash! Again, his code produces tiles are incompatible with ⬆️ BCs (in @yvikhlya's area).

@yvikhlya has copied my set to his area (Dec 16 1400 local time). So if you use:
- restarts: `/discover/nobackup/sakella/restarts/test_23Nov2022/output/`
- BCs that are same as `/discover/nobackup/sakella/BCs/test_23Nov2022/MOM6/${OGCM_IM}x${OGCM_JM}` But in @yvikhlya area (that he just refreshed)

all should ✅

**Comment by sanAkel** [comment]
Is this resolved?

If it is, please close it.
