### ISSUE TITLE
GOCART Data is broken with new MBundle

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#579]
The new mbundle code from @atrayano and @bena-nasa seems to have broken GOCART Data:

```
 Real*4 Resource Parameter: SATSIM_DT:3600.000000
pe=00090 FAIL at line=00136    MBundle_IncrementMod.F90                 <DU::DU is not valid. It likely does not exist in MTR>
pe=00090 FAIL at line=01952    GEOS_PhysicsGridComp.F90                 <status=1>
pe=00090 FAIL at line=01861    MAPL_Generic.F90                         <status=1>
pe=00090 FAIL at line=01315    MAPL_Generic.F90                         <status=1>
pe=00090 FAIL at line=01087    MAPL_Generic.F90                         <status=1>
```

This new code confuses me enough that I didn't know where to put this issue. I'm not sure if it's a GCM GridComp or GEOSgcm_App issue. So we make it "generic".

CC: @sdrabenh

**Comment by bena-nasa** [comment]
@pcolarco
I'm pretty sure we can disable this if GOCART2G.data. I will see if I can and report back here. As the question if whatever this is doing, is something that even makes sense when running GOCART2G.data, that a question for a scientist (@amdasilva )who understands what this is reporting and if that is even reportable when running GOCART2G.data

**Comment by bena-nasa** [comment]
@pcolarco @sdrabenh @mathomp4 
Yes it can be disabled. You need to comment out:
```
# Enable wet scavenging
MTRI_increments::
DU::DU default
SS::SS default
SU::SO4 default
CA.bc::CA.bcphilic default
CA.br::CA.brphilic default
CA.oc::CA.ocphilic default
NI::NO3an1 "NI::NO3an2,NI::NO3an3"
::
```
and in History remove these fields from whatever collection they are in
```
                               'MTRI%DU::DUIM'             , 'PHYSICS' , 'DUSV' ,
                               'MTRI%SS::SSIM'             , 'PHYSICS' , 'SSSV' ,
                               'MTRI%CA.oc::CA.ocphilicIM' , 'PHYSICS' , 'OCSV' ,
                               'MTRI%CA.bc::CA.bcphilicIM' , 'PHYSICS' , 'BCSV' ,
                               'MTRI%CA.br::CA.brphilicIM' , 'PHYSICS' , 'BRSV' ,
                               'MTRI%SU::SO4IM'            , 'PHYSICS' , 'SUSV' ,
                               'MTRI%NI::NO3an1IM'         , 'PHYSICS' , 'NISV' ,
```

**Comment by bena-nasa** [comment]
I just created new issue #581. This exposes a whole new can of worms
