### ISSUE TITLE
Chemistry species tendency diagnostics

### ISSUE THREAD

**Issue by gmao-esherman** [GEOS-ESM/GEOSgcm#61]
A zero-diff code change is proposed for GEOSchem_GridComp which would allow for convenient output of tendency diagnostics of all chemistry species with respect to Turbulence, Moist (convection), Dynamics, Water Mass rescaling, and Chemistry. It would also allow for chemical species with identical names to exist in two or more GridComps (e.g. StratChem and TR can both contain SF6). 

This change involves edits in 5 different repositories (GEOSchem_GridComp, GEOSgcm_GridComp, GEOSgcm_App, FVdycoreCubed_GridComp and MAPL) which will involve coordinated efforts of the gate-keepers. It also involves syntax/name changes for 2 diagnostic fields in HISTORY.rc (OXIM and OXIT). We have run GEOS zero diff tests and the result are zero-diff. gcm_regress.j also ran successfully.

**Comment by tclune** [comment]
@wmputman This is a big zero-diff change from the chemistry folk.   Needs your approval to proceed.

**Comment by wmputman** [comment]
With the transition now to GIT it will require that we formalize some processes for getting large code updates onto develop.  We need to have a code summary and review with appropriate attendance from the relevant gatekeepers.  For this request we need at least @wmputman @gmao-esherman @sdrabenh and @lltakacs at the meeting.  I'd like to target Monday/Friday afternoons for these code meetings. I will send a meeting request for 12:30pm Oct 18. If there are others who should be invited please include them.

**Comment by mathomp4** [comment]
@gmao-esherman I believe we can now close this, correct?

**Comment by gmao-esherman** [comment]
Yes.
