### ISSUE TITLE
cannot find data_table error

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/GEOSgcm#668]
### Minor Problem:

Using `gcm_setup` with default settings + coupled setup `MOM6` (`540X458`) and `CICE4` gives:

<img width="967" alt="Screenshot 2023-10-09 at 1 31 57 PM" src="https://github.com/GEOS-ESM/GEOSgcm/assets/38666458/4506bd07-c6df-491f-9adb-9c77a73f85a0">

Same setup with MOM6 `1440x1080` does not have this issue, so it might be related to `INPUT` files somewhere.

### Suggested solution: 

For default runs, `data_table` is empty so having an empty `data_table` file in `../install/bin` solves this issue.

**Comment by mathomp4** [comment]
Hmm. I'll let @sanAkel and @zhaobin74 comment on this. Coupled is still a mystery to me. :)

**Comment by zhaobin74** [comment]
Yes, ```data_table``` (an empty one good enough) is missing for ```540x458``` configuration.  I have to manually add it in ```install/etc``` directory after a build is done.  It should come from mom6_app/540x458. Feel free to submit a PR. Thanks.

**Comment by sanAkel** [comment]
@Dooruk you need to make following happen before the model runs:

`touch data_table`

**Comment by Dooruk** [comment]
I have a similar error which can be solved by :

`Unable to open INPUT/MOM_channels_global_tx06v1`

I wasn't able to locate this channel file anywhere.

**Comment by sanAkel** [comment]
> I have a similar error:
> 
> `Unable to open INPUT/MOM_channels_global_tx06v1`
> 
> I wasn't able to locate this channel file anywhere.
> 
```
cp /discover/nobackup/sakella/MOM6-GFDL/MOM6-testing/Gustavo.Marques/datasets/MOM_channels_global_tx06v1 <your_exp_path>
```

> @sanAkel the original error is when `gcm_setup` is executed not `gcm_run`

Of course! You need to provide some `data_table` file, contents are immaterial, just a file with such a **name** for the model to run. You can ignore those errors from `gcm_setup`.
