### ISSUE TITLE
Slight difference in some aerosol HISTORY output

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#68]
@gmao-esherman and @adarmenov,

I'm tagging you guys first as what I'm seeing is aerosol based. I think it's from something @adarmenov passed in, but I figure you are the two experts.

To wit, I came back from leave seeing this in my nightly tests:
```
github             --   pass  26 min      --   --   pass/FAIL/ --   -- / --   --   pass/pass    pass      --     
githubrep         SKIP   --    --         --   --   pass/FAIL/ --   -- / --   --    -- / --     pass      --     
githubdebug        --   pass   8 min      --   --   pass/FAIL/ --   -- / --   --    -- / --     pass      --     
```
Odd. I still got many a notification on my iPhone from Git and I didn't remember @sdrabenh  or @lltakacs making any non-zero-diff pulls. But I was wasn't paying attention too hard either.

So I go look at the cmp logs and everything is zero-diff except `tavg2d_aer`:
```
 Comparing GCM run restarts...
                              gocart_internal_rst:  PASSED.
                               irrad_internal_rst:  PASSED.
                                lake_internal_rst:  PASSED.
...
             1day.tavg2d_aer_x.20000415_0900z.nc4: [FAILED]*!?#$*
             1day.tavg3d_aer_p.20000415_0900z.nc4:  PASSED.
```
All the restarts are zero-diff and all the history output but for `tavg2d_aer`. If I do a comparison myself:
```
(1056) $ nccmp -BdqfS BASELINE/run/1day/holding/tavg2d_aer_x/200004/1day.tavg2d_aer_x.20000415_0900z.nc4 \
CURRENT/run/1day/holding/tavg2d_aer_x/200004/1day.tavg2d_aer_x.20000415_0900z.nc4 
Variable Group Count         Sum      AbsSum          Min         Max       Range        Mean      StdDev
BCSV     /     16380 5.59925e-15  5.5994e-15 -7.24497e-20 3.27172e-17 3.27897e-17 3.41835e-19 1.45189e-18
DUSV     /     13304 2.39448e-12 2.39448e-12 -6.52063e-20 3.46885e-14 3.46886e-14 1.79982e-16 1.46602e-15
OCSV     /     16380 5.11319e-14 5.11319e-14 -7.03877e-23 6.80825e-16 6.80825e-16  3.1216e-18 1.79945e-17
SSSV     /     16373 7.27088e-12 7.27088e-12  -7.6949e-37 4.90176e-15 4.90176e-15 4.44077e-16 6.46015e-16
SUSV     /      9144 9.89312e-15 1.03452e-14  -1.1099e-17 7.55491e-17  8.6648e-17 1.08192e-18 2.94461e-18
```
If you trace this in the code, it looks like these are Moist exports and my guess is the difference is from GEOS-ESM/GEOSgcm_GridComp#94. It looks like just a slight math order change because the compiler might be able to do less/different optimizing as the divide by `MAPL_GRAV*DT_MOIST` is now in a second step and not all in one step.

I just wanted some reassurance before I re-baseline my nightly tests that this is just really an artifact of the Moist changes.

**Comment by adarmenov** [comment]
@mathomp4 If this is related to GEOS-ESM/GEOSgcm_GridComp#94 then you should re-baseline.
