### ISSUE TITLE
v12 C540 runs die in dynamics

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GEOSgcm#824]
I was trying to run a C540 run recently because @mmanyin and others are interested in it.

We know there is an issue in MAPL between the stretched grid and point emissions (see https://github.com/GEOS-ESM/MAPL/issues/2850), so I made a C540 run where all the volcanoes were turned off. However, even with that, my run dies at the *first* step with:

```
 Integer*4 Resource Parameter: INTERPOLATE_OCEAN_ICE_CURRENTS:0, (default value)
 AGCM Date: 2020/04/14  Time: 21:05:00  Throughput(days/day)[Avg Tot Run]:          4.4          4.4         13.5  TimeRemaining(Est) 005:26:20   64.3% :  49.8% Mem Comm:Used
pe=03592 FAIL at line=03533    DynCore_GridCompMod.F90                  <negative water vapor detected>
pe=03234 FAIL at line=03533    DynCore_GridCompMod.F90                  <negative water vapor detected>
SUPERDYNAMICSRun                               743
AGCMRun                                       2558
GCMRun                                        2069
```

Since it dies so fast, my thought is I probably have crappy restarts. I'll consult with @wmputman

**Comment by mmanyin** [comment]
@mathomp4 Is it clear then that v11 doesn't support stretched grid, so you're moving on to v12?

**Comment by mathomp4** [comment]
> @mathomp4 Is it clear then that v11 doesn't support stretched grid, so you're moving on to v12?

@mmanyin Oh. v11 might work. I just ... didn't try it. (I had a v12 build around). Time for a new experiment! 😄

**Comment by mathomp4** [comment]
We have an update. @wmputman noticed an issue with v12. With v11 it works because `NCAR_NRDG` is 0 in v11 by default, but in v12 it is not if we are not running 72 levels. 

This all has to do with the GWD Ridge files, which we only have for certain resolutions (at the moment, @bena-nasa is working on figuring out how to get more). So, I'm looking to add run-time support where *if* we have a ridge file, we do nothing, but if we don't, we add `NCAR_NRDG: 0` to `AGCM.rc`
